/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mcacisi;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import mcacisi.features.removeGui;
import mcacisi.features.searchGui;

/**
 * Use the Array list to store student objects for temp, then save them on a file
 *
 * @author Mcacisi Sithole
 */
public class StudentApp extends javax.swing.JFrame {

    private ArrayList<Student> arrStud = new ArrayList<>();

    /**
     * Creates new form StudentApp
     */
    public StudentApp() {
        initComponents();
        reloadStudentFromFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JToggleButton();
        btnViewAll = new javax.swing.JToggleButton();
        btnClear = new javax.swing.JToggleButton();
        btnExit = new javax.swing.JToggleButton();
        txtStudentNo = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtInitials = new javax.swing.JTextField();
        cmbCourse = new javax.swing.JComboBox<>();
        cmbYearOfStudy = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDisplay = new javax.swing.JTextArea();
        btnSearch = new javax.swing.JToggleButton();
        btnUpdate = new javax.swing.JToggleButton();
        btnRemove = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student  Course Registration System");
        setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setText("Student Number :");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Lastname :");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("Initials :");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setText(" Course :");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setText("Year Of Study :");

        btnRegister.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnViewAll.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnViewAll.setText("View All");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnClear.setText("Clear Fields");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                          -- SELECT COURSE --", "ACCOUNTING", "AGRICULTURAL MANAGEMENT", "ANALYTICAL CHEMISTRY", "FASHION", "HUMAN RESOURCE MANAGEMENT", "INFORMATION OF TECHNOLOGY", "CHEMICAL ENGINEERING", "CIVIL ENGINEERING ", "ELECTRONIC ENGINEERING", "MECHANICAL ENGINEERING", "INDUSTRIAL ENGINEERING", "POWER ENGINEERING", "MARKETING", "LABOUR LAW", "POLICING", "SAFETY MANAGEMENT", "TEACHING (SENIOR PHASE & FET)", "TOURISM" }));

        cmbYearOfStudy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        lblDisplay.setColumns(20);
        lblDisplay.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lblDisplay.setRows(5);
        jScrollPane1.setViewportView(lblDisplay);

        btnSearch.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnClear))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbYearOfStudy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbCourse, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLastname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                .addComponent(txtInitials)))))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtInitials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbYearOfStudy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewAll, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 194, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String studNo, lastname, initials, course;
        int yearOfStudy;

        
        studNo = txtStudentNo.getText().trim();
                if(studNo.isEmpty() || studNo.length()< 9){
                    JOptionPane.showMessageDialog(this, "Please enter student number", "Missing Data input", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                
        lastname = txtLastname.getText().toUpperCase().trim();
                if(lastname.isEmpty()){
                   JOptionPane.showMessageDialog(this, "Please enter your lastname", "Missing Data input", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                
        initials = txtInitials.getText().toUpperCase().trim();
                if(initials.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter your Initials", "Missing Data input", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                
         yearOfStudy =  Integer.parseInt((String)cmbYearOfStudy.getSelectedItem());
         
         
        course = (String) cmbCourse.getSelectedItem();
                if(cmbCourse.getSelectedIndex()==0){
                    JOptionPane.showMessageDialog(this, "Please select the appropriate course", "Course selection", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                 
                


        
        for (Student ms : arrStud) {
            if (ms.getStudentNo().equals(studNo)) {
                JOptionPane.showMessageDialog(this, "Student Number already exists", "Duplicate students", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        Student myStud = new Student(studNo, lastname, initials, yearOfStudy, course);
        arrStud.add(myStud);
        JOptionPane.showMessageDialog(this, "Student registered successfully", "", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtStudentNo.setText("");
        txtLastname.setText("");
        txtInitials.setText("");
        cmbCourse.setSelectedIndex(0);
        cmbYearOfStudy.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnClearActionPerformed

    
    
    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed

        StringBuilder my = new StringBuilder();
        my.append(String.format("%-15s %-15s %-15s %-10s %-20s\n", "STUDENTNO", "SURNAME", "INITIALS", "YEAR", "COURSE"));
        my.append("________________________________________________________________________________________________________________________________\n");
        
        for(Student s: arrStud){
            my.append(String.format("%-15s %-15s %-15s %-10d %-30s\n", 
                      s.getStudentNo(),
                      s.getInitials(),
                       s.getLastname(),
                       s.getYearOfStudy(),
                       s.getCourse()));
            
        }
        
        lblDisplay.setText(my.toString());
    }//GEN-LAST:event_btnViewAllActionPerformed

    
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

       searchGui search = new searchGui(arrStud); 
       search.setVisible(true);
       
    }//GEN-LAST:event_btnSearchActionPerformed

    
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String updateStud;
        String newLastname, newInitials, newCourse;
        int newYearOfStudy;
        boolean foundStud = false;
        
        updateStud = txtStudentNo.getText().trim();
                     if(updateStud.isEmpty() || updateStud.length()< 9){
                         JOptionPane.showMessageDialog(this, "Please enter student number", "Missing data input", JOptionPane.INFORMATION_MESSAGE);
                     }
                     
        newLastname = txtLastname.getText();
        newInitials = txtInitials.getText();
        newYearOfStudy = Integer.parseInt((String) cmbYearOfStudy.getSelectedItem());
        newCourse = (String)cmbCourse.getSelectedItem();
        
        
        
        for(Student s: arrStud){
            if(s.getStudentNo().equalsIgnoreCase(updateStud)){
                foundStud = true;
                
                
               s.setLastname(newLastname.toUpperCase().trim());
               s.setInitials(newInitials.toUpperCase().trim());
               s.setYearOfStudy(newYearOfStudy);
               s.setCourse(newCourse);
            }
        }
        
            
            if(foundStud){
               btnViewAllActionPerformed(null);
             JOptionPane.showMessageDialog(this, "Student record updated successfully"); 
             
             
            } else if(updateStud.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please enter student number");   
             
             
            } else{
                JOptionPane.showMessageDialog(this, "Student was not found in list", "SearchStudent", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btnUpdateActionPerformed

   
    
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        removeGui remove = new removeGui(arrStud);
        remove.setVisible(true);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
     int response;
       
       response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit", JOptionPane.YES_NO_OPTION);
       
                 if(response == JOptionPane.YES_OPTION){
                    this.dispose();
                 }
    }//GEN-LAST:event_btnExitActionPerformed

    
    
    //Method to save student objects into a binary file
    public void saveToFile(){
        
    }
    
    
    //Method to reload binary file data bact into arraylist to display
    public void reloadStudentFromFile(){
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnClear;
    private javax.swing.JToggleButton btnExit;
    private javax.swing.JToggleButton btnRegister;
    private javax.swing.JToggleButton btnRemove;
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JToggleButton btnUpdate;
    private javax.swing.JToggleButton btnViewAll;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JComboBox<String> cmbYearOfStudy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblDisplay;
    private javax.swing.JTextField txtInitials;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtStudentNo;
    // End of variables declaration//GEN-END:variables
}
