/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mcacisi.features;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import mcacisi.Student;

/**
 *
 * @author Mcacisi Sithole
 */
public class removeGui extends javax.swing.JFrame {
    
     private ArrayList <Student> arrStud = new ArrayList<> ();
     
    /**
     * Creates new form removeGui
     */
    public removeGui(ArrayList <Student> arrStud) {
        this.arrStud = arrStud;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEnterStudentNumber = new javax.swing.JTextField();
        btnRemoveStudent = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REMOVE_FORM");

        jLabel1.setText("ENTER STUDENT NUMBER");

        btnRemoveStudent.setText("REMOVE_STUDENT");
        btnRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoveStudent)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtEnterStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEnterStudentNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(btnRemoveStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStudentActionPerformed
        String studNo;
        Student removeStud = null;
        int response;
        boolean found = false;
        
        
        studNo = txtEnterStudentNumber.getText().trim();
                if(studNo.isEmpty()){
                   JOptionPane.showMessageDialog(this, "Please enter student number", "Missing data input", JOptionPane.INFORMATION_MESSAGE);
                }
                
                
                for(Student stud : arrStud){
                   if(stud.getStudentNo().equals(studNo)){
                      found = true;
                      removeStud = stud;
                      
                    }else{
                       JOptionPane.showMessageDialog(this, "Student not found", "Registered students", JOptionPane.INFORMATION_MESSAGE);
                   }        
                }
                
                
                
                if(found){
                   response = JOptionPane.showConfirmDialog(this, "Do you want to remove student?", "Remove registered student", JOptionPane.YES_NO_OPTION);
                   if(response == JOptionPane.YES_OPTION){
                       arrStud.remove(removeStud);
                       JOptionPane.showMessageDialog(this, "Student removed successfully", "Remove student", JOptionPane.INFORMATION_MESSAGE);
                   }
                }
    }//GEN-LAST:event_btnRemoveStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnRemoveStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEnterStudentNumber;
    // End of variables declaration//GEN-END:variables
}
