/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mcacisi.features;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import mcacisi.StudentPD;

/**
 *
 * @author Mcacisi Sithole
 */
public class removeGui extends javax.swing.JFrame {
    
     private ArrayList <StudentPD> arrStud = new ArrayList<> ();
     
    /**
     * Creates new form removeGui
     */
    public removeGui(ArrayList <StudentPD> arrStud) {
        this.arrStud = arrStud;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEnterStudentNumber = new javax.swing.JTextField();
        btnRemoveStudent = new javax.swing.JToggleButton();
        btnClear = new javax.swing.JToggleButton();
        btnExit = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REMOVE_FORM");

        jLabel1.setText("ENTER STUDENT NUMBER");

        btnRemoveStudent.setText("REMOVE_STUDENT");
        btnRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStudentActionPerformed(evt);
            }
        });

        btnClear.setText("Clear Fields");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveStudent))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEnterStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnterStudentNumber))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemoveStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStudentActionPerformed
        String studNo;
        StudentPD removeStud = null;
        int response;
        boolean found = false;
        
        
        
    try
       {
        studNo = txtEnterStudentNumber.getText().trim();
                if(studNo.isEmpty() || studNo.length()< 9){
                   JOptionPane.showMessageDialog(this, "Please enter student number\n StudentPD number consist of 9 characters", "Missing data input", JOptionPane.INFORMATION_MESSAGE);
                   return;
                }
                
                Integer.parseInt(studNo);
                
       }catch(NumberFormatException e){
             JOptionPane.showMessageDialog(this, "Only integers will be accepted as student number\n Alphabets are not allowed", "StudentNo input Error", JOptionPane.INFORMATION_MESSAGE);
               return;
    }         
                
                
                
                
                for(StudentPD stud : arrStud){
                   if(stud.getStudentNo().equals(studNo)){
                      found = true;
                      removeStud = stud;
                      
                    }else{
                       JOptionPane.showMessageDialog(this, "StudentPD was not found", "Registered students", JOptionPane.INFORMATION_MESSAGE);
                   }        
                }
                
                
                
                if(found){
                   response = JOptionPane.showConfirmDialog(this, "Do you want to remove student?", "Remove registered student", JOptionPane.YES_NO_OPTION);
                   
                   
                   if(response == JOptionPane.YES_OPTION){
                       arrStud.remove(removeStud);
                       JOptionPane.showMessageDialog(this, "StudentPD removed successfully", "Remove student", JOptionPane.INFORMATION_MESSAGE);
                       
                   } else {
                       JOptionPane.showMessageDialog(this, "StudentPD not removed in list", "Remove StudentPD", JOptionPane.INFORMATION_MESSAGE);
                   }
                   
                }
    }//GEN-LAST:event_btnRemoveStudentActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtEnterStudentNumber.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnClear;
    private javax.swing.JToggleButton btnExit;
    private javax.swing.JToggleButton btnRemoveStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEnterStudentNumber;
    // End of variables declaration//GEN-END:variables
}
