/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mcacisi.features;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import mcacisi.Student;

/**
 *
 * @author Mcacisi Sithole
 */
public class searchGui extends javax.swing.JFrame {

    private ArrayList<Student> arrStud = new ArrayList<> ();
    
    
    public searchGui(ArrayList <Student> arrStud) {
        this.arrStud = arrStud;
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEnterStudentNumber = new javax.swing.JTextField();
        btnSearchStudent = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEARCH_FORM");

        jLabel1.setText("ENTER STUDENT NUMBER");

        txtEnterStudentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterStudentNumberActionPerformed(evt);
            }
        });

        btnSearchStudent.setText("SEARCH_STUDENT");
        btnSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchStudent)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEnterStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnterStudentNumber))
                .addGap(18, 18, 18)
                .addComponent(btnSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnterStudentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterStudentNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterStudentNumberActionPerformed

    
    
    
    private void btnSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStudentActionPerformed
        String studNo;
        boolean found = false;
        
        studNo = txtEnterStudentNumber.getText().trim();
        
        
        for(Student stud:arrStud){
            if(stud.getStudentNo().equals(studNo)){
               found = true;
            }
        }
        
        
        
        if(found){
            JOptionPane.showMessageDialog(this, "Student found in list","searchStud", JOptionPane.INFORMATION_MESSAGE);
        } else {
             JOptionPane.showMessageDialog(this, "Student does not exists ","searchStud", JOptionPane.INFORMATION_MESSAGE);
        
        }
        
    }//GEN-LAST:event_btnSearchStudentActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSearchStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEnterStudentNumber;
    // End of variables declaration//GEN-END:variables
}
